train:
    max_epoch: 100
    max_batches: 500
    batch_size: 16
    seed: 123456
    write_graph: False
    log_interval: 10
    eval_interval: 100
    resume_file: null  # like "data/trainer.gz"
    # resume_file: "data/trainer.gz"
    trained_file: "data/trainer.gz"
    save_in_last: True
    eval:
        max_batches: 50

model:
    transformer:
        decoder:
            nhead: 8
            num_layers: 3
            add_noise: True
