train:
    max_epoch: 10
    max_batches: 5000
    batch_size: 16
    seed: 123456
    write_graph: False
    log_interval: 10
    eval_interval: 100
    resume_file: null  # like "data/trainer.gz"
    trained_file: "data/trainer.gz"

model:
    transformer:
        decoder:
            nhead: 8
            num_layers: 3
