slack:
    server:
        localdb:
            do_store: true
        action:
            hello:
                patterns:
                    - ["^hello$", "hello!!"] 
                    - ["^OK[!?]+$", "it's OK!!"] 
    client:
        replying_server:
            base_url: "http://tkosht.f5.si:7777"
