services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED=2
      - OLLAMA_NUM_THREADS=8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
      - ./data/deepseek:/deepseek
    tty: true
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: $pj_name.neo4j
    environment:
      - TZ=Asia/Tokyo
      - NEO4J_AUTH=$neo4j_user/$neo4j_pswd
      - NEO4JLABS_PLUGINS=["apoc"]
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/var/lib/neo4j/plugins
      - ./conf/:/conf
    ports:
      - "7575:7474"     # for HTTP
      - "7676:7687"     # for Bolt
    # restart: always

