version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.gpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $pj_name.app
    container_name: $pj_name.app
    tty: true
    init: true
    privileged: true
    # network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]
    volumes:
      - .:/home/$user_name/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ~/.Xauthority:/home/$user_name/.Xauthority
      - /run/user/1000/bus:/run/user/1000/bus
      - /run/snapd.socket:/run/snapd.socket
    working_dir: /home/$user_name/workspace
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - NVIDIA_DRIVER_CAPABILITIES=all
       #- DISPLAY=localhost:10.0
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    # sysctls:
    #   - net.core.somaxconn=$somaxconn
    #   - net.ipv4.tcp_syncookies=0
    # ports:
    #   - "2022:22"   # ssh
    #   - "5000:5000" # MLflow
    #   - "5656:5656" # sqlite-web
    #   - "6006:6006" # tensorboard
    #   - "7860:7860" # gradio
    #   - "8501:8501" # streamlit
    #   - "8000:8000" # webapi
    #   - "8080:8080" # vue
    #   - "9229:9229" # node debugger

  postgresql:
    image: postgres:latest
    container_name: $pj_name.postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=campfire_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"     # postgresql

  neo4j:
    image: neo4j:latest
    container_name: $pj_name.neo4j
    build:
      context: ./
      dockerfile: docker/Dockerfile.neo4j
    environment:
      - NEO4J_AUTH=$neo4j_user/$neo4j_pswd
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/var/lib/neo4j/plugins
      # - ./conf:/var/lib/neo4j/conf
    ports:
      - "7474:7474"   # for HTTP
      - "7687:7687"   # for Bolt

