version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: app.$pj_name
    container_name: app.$pj_name
    tty: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    ports:
      - "5000:5000"   # MLflow
      - "6006:6006"   # tensorboard
      - "8000:8000"   # webapi
      - "8080:8080"   # vue
      - "9229:9229"   # node debugger
  neo4j:
    image: neo4j:latest
    container_name: neo4j.$pj_name
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./conf:/var/lib/neo4j/conf
      - ./data/neo4j/plugins:/plugins
    ports:
      - "7474:7474"   # for HTTP
      - "7687:7687"   # for Bolt
